GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/63e9677e1f85a3f69a68f2cb
###
DELETE http://localhost:3001/api/persons/63e9677e1f85a3f69a68f2cb
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Random Person",
    "number": "09-1234556"
}
### Unknown endpoint middleware
GET http://localhost:3001/api/xyz
### PUT
PUT http://localhost:3001/api/persons/63ea1b8b5703b327184bb6f4
content-type: application/json

{
    "name": "Random Person?",
    "number": "103-3344551"
}