GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/63e982c5258250626ecb6e60
###
DELETE http://localhost:3001/api/persons/63e982c5258250626ecb6e60
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Random Person",
    "number": "09-1234556"
}
### Unknown endpoint middleware
GET http://localhost:3001/api/xyz
### PUT
PUT http://localhost:3001/api/persons/63ea27f3bbb5888cc4e58b85
content-type: application/json

{
    "name": "Random Person?",
    "number": "103-3344551"
}