GET http://localhost:3001/api/persons
###
GET http://localhost:3001/info
###
GET http://localhost:3001/api/persons/63e9677e1f85a3f69a68f2cb
###
DELETE http://localhost:3001/api/persons/63e9677e1f85a3f69a68f2cb
###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Random Person",
    "number": "43-57-123456"
}
### Unknown endpoint middleware
GET http://localhost:3001/api/xyz
### PUT
PUT http://localhost:3001/api/persons/6dd978f20513e0924c847aeb
content-type: application/json

{
    "name": "New Phonee, Who Dis?",
    "number": "43-57-123456"
}